In [1]:
'''Benchmark #2'''

'''
add onto benchmark #1 by now introducing a few shape objects 
into the system

the canvas algorithm will go, and then the shape algorithm will go

test to see how much the evolution is affected by the order of 
shapes placed onto the canvas

shape objects can vary in size, location, and RGBA color
'''

import math
import random
import imgcompare
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw

In [2]:
class Hyperparameters:
    '''
    '''
    HYPERPARAMETER = 0

In [3]:
class Canvas:
    '''
    - handles only the background color of the painting
    '''
    def __init__(self) -> None:
        self.color = self.define_color()
    
    def __str__(self) -> str:
        return "Color: {}".format(self.color)
    
    def define_color(self) -> list:
        R = random.randint(0, 255)
        G = random.randint(0, 255)
        B = random.randint(0, 255)
        return [R, G, B]


if __name__ == "__main__":
    canvases = [Canvas() for _ in range(0, 10)]
    for canvas in canvases: print("{}".format(canvas))

Color: [130, 1, 88]
Color: [207, 123, 211]
Color: [195, 19, 123]
Color: [13, 78, 85]
Color: [71, 209, 220]
Color: [124, 53, 58]
Color: [177, 231, 25]
Color: [93, 54, 148]
Color: [207, 234, 81]
Color: [105, 17, 111]


In [4]:
class Shape:
    '''
    - circles
    '''
    def __init__(self, width: int, height: int, factor: float) -> None:
        self.width = width
        self.height = height
        self.factor = factor
        self.color = self.define_color()
        self.radius = int(0.5 * random.gammavariate(self.factor, 0.1 * self.get_hypotenuse()))
        self.center = [random.randint(0, self.width - 1), random.randint(0, self.height - 1)]
    
    def __str__(self) -> str:
        '''
        - reads out key specs fo the shape -> (color, center coordinate, radius)
        '''
        return "Color: {0}; Radius: {1}; Center: {2}".format(self.color, self.radius, self.center)
    
    def crossover(self):
        pass
    
    def define_color(self) -> list:
        R = random.randint(0, 255)
        G = random.randint(0, 255)
        B = random.randint(0, 255)
        A = random.randint(0, 255)
        return [R, G, B, A]
    
    def define_drawing_coordinates(self) -> list:
        '''
        - the drawing tool requires the shape's boundary coordinates in order to draw
        - the shape's center coordinate and radius are used to compute the boundary points
        '''
        x0 = self.center[0] - self.radius # 180 deg position
        x1 = self.center[0] + self.radius #   0 deg position
        y0 = self.center[1] - self.radius # 270 deg position
        y1 = self.center[1] + self.radius #  90 deg position
        return [x0, y0, x1, y1]
    
    def draw_circle(self, drawing_tool: object) -> None:
        '''
        - using the PIL library, this function draws an ellipse with symmetrical 
          coordinates, thus drawing a circle
        - the drawing tool is defined in the Painting object
        '''
        drawing_tool.ellipse(tuple(self.define_drawing_coordinates()), tuple(self.color))
    
    def get_hypotenuse(self) -> int:
        return int(math.sqrt((self.width) ** 2 + (self.height) ** 2))

if __name__ == "__main__":
    WIDTH, HEIGHT, FACTOR = 400, 400, 1
    shapes = [Shape(WIDTH, HEIGHT, FACTOR) for _ in range(0, 10)]
    for shape in shapes: print("{}".format(shape))

Color: [25, 226, 249, 87]; Radius: 47; Center: [377, 203]
Color: [220, 4, 120, 222]; Radius: 6; Center: [44, 388]
Color: [74, 234, 130, 80]; Radius: 16; Center: [234, 277]
Color: [234, 222, 174, 154]; Radius: 31; Center: [360, 377]
Color: [186, 129, 202, 66]; Radius: 13; Center: [362, 155]
Color: [33, 207, 11, 143]; Radius: 8; Center: [22, 256]
Color: [31, 112, 236, 56]; Radius: 7; Center: [237, 190]
Color: [137, 213, 155, 230]; Radius: 2; Center: [212, 265]
Color: [48, 169, 78, 18]; Radius: 53; Center: [199, 347]
Color: [75, 36, 216, 222]; Radius: 53; Center: [36, 274]


In [10]:
class Painting:
    '''
    '''
    def __init__(self, width: int, height: int, size: int) -> None:
        self.width = width
        self.height = height
        self.size = size
        self.canvas_genotype = Canvas()
        self.shape_genotype = [Shape(width = self.width,
                                     height = self.height,
                                     factor = 2) for _ in range(0, self.size)]

        self.overall_fitness = 0
        self.r_fitness = 0
        self.g_fitness = 0
        self.b_fitness = 0
        self.create_painting()
    
    def create_painting(self) -> None:
        self.sort_genotype(mode = '5')
        self.phenotype = Image.new(mode = 'RGB',
                                   size = (self.width, self.height),
                                   color = tuple(self.canvas_genotype.color))
        self.draw = ImageDraw.Draw(self.phenotype, 'RGBA')
        for shape in self.shape_genotype: shape.draw_circle(self.draw)
    
    def show_painting(self) -> None:
        self.phenotype.show()
    
    def save_painting(self, painting_id: int) -> None:
        '''
        - saves the populated image as a png file
        '''
        self.phenotype.save('../lib/benchmark2_test/test_painting{}.png'.format(str(painting_id)))
    
    def crossover(self, parent_canvas_gen: object, parent_shape_gen: object, mutation_rate: float) -> object:
        child = Painting(width = self.width, height = self.height, size = self.size)
        # CANVAS CROSSOVER
        child.canvas_genotype.color[0] = int(0.5 * (self.canvas_genotype.color[0] + parent_canvas_gen.color[0]))
        child.canvas_genotype.color[1] = int(0.5 * (self.canvas_genotype.color[1] + parent_canvas_gen.color[1]))
        child.canvas_genotype.color[2] = int(0.5 * (self.canvas_genotype.color[2] + parent_canvas_gen.color[2]))
        # SHAPE CROSSOVER
        if random.choice([0, 1]) == 0:
            '''
            - the first half of parent 1 is combined with the second half of parent 2
            '''
            parent1_traits = self.shape_genotype[: int(len(self.shape_genotype) / 2)]
            parent2_traits = parent_shape_gen[int(len(parent_shape_gen) / 2) :]
            child.shape_genotype = parent1_traits + parent2_traits
        else:
            '''
            - the second half of parent 1 is combined with the first half of parent 2
            '''
            parent1_traits = self.shape_genotype[int(len(self.shape_genotype) / 2) :]
            parent2_traits = parent_shape_gen[: int(len(parent_shape_gen) / 2)]
            child.shape_genotype = parent1_traits + parent2_traits
        child.canvas_mutate(mutation_rate = mutation_rate)
        child.shape_mutate(mutation_rate = mutation_rate, mode = '5')
        return child
    
    def canvas_mutate(self, mutation_rate: float) -> None:
        for index in range(0, len(self.canvas_genotype.color)):
            if random.randint(1, int(1 / mutation_rate)) == 1:
                self.canvas_genotype.color[index] = self.canvas_genotype.color[index] + random.randint(-30, 30)
    
    def shape_mutate(self, mutation_rate: float, mode: str) -> None:
        '''
        | specs:
        | - design in modes to compare methods
        | - "for" = for shape in shapes...
        | - "if" = if a shape is to be mutated or not
        | - "choose" = choose one of the mutation types
        | - extensive documentation!!!
        '''
        mutation_types = ['shape', 'gene']
        weights = [0.99, 0.01]
        mutation = random.choices(mutation_types, weights = weights, k = 1)[0]
        if mutation == 'shape':
            if mode == '1':
                ''' for -> if -> choose'''
                for shape in self.shape_genotype:
                    if random.randint(1, int(1 / mutation_rate)) == 1:
                        shape_mut_types = ['radius', 'shift', 'R', 'G', 'B', 'A']
                        shape_weights = [0.10, 0.10, 0.20, 0.20, 0.20, 0.20]
                        shape_mutation = random.choices(shape_mut_types, 
                                                        weights = shape_weights, 
                                                        k = 1)[0]
                        self.choose_mutation(obj = shape, mut_type = shape_mutation)
            elif mode == '2':
                ''' for -> choose -> if'''
                for shape in self.shape_genotype:
                    shape_mut_types = ['radius', 'shift', 'R', 'G', 'B', 'A']
                    shape_weights = [0.10, 0.10, 0.20, 0.20, 0.20, 0.20]
                    shape_mutation = random.choices(shape_mut_types, 
                                                    weights = shape_weights, 
                                                    k = 1)[0]
                    if random.randint(1, int(1 / mutation_rate)) == 1:
                        shape.choose_mutation(obj = shape, mut_type = shape_mutation)
            elif mode == '3':
                ''' choose -> for -> if'''
                shape_mut_types = ['radius', 'shift', 'R', 'G', 'B', 'A']
                shape_weights = [0.10, 0.10, 0.20, 0.20, 0.20, 0.20]
                shape_mutation = random.choices(shape_mut_types, 
                                                weights = shape_weights, 
                                                k = 1)[0]
                for shape in self.shape_genotype:
                    if random.randint(1, int(1 / mutation_rate)) == 1:
                        shape.choose_mutation(obj = shape, mut_type = shape_mutation)
            elif mode == '4':
                ''' choose -> if -> for'''
                shape_mut_types = ['radius', 'shift', 'R', 'G', 'B', 'A']
                shape_weights = [0.10, 0.10, 0.20, 0.20, 0.20, 0.20]
                shape_mutation = random.choices(shape_mut_types, 
                                                weights = shape_weights, 
                                                k = 1)[0]
                if random.randint(1, int(1 / mutation_rate)) == 1:
                    for shape in self.shape_genotype:
                        shape.choose_mutation(obj = shape, mut_type = shape_mutation)
            elif mode == '5':
                '''if -> choose -> for'''
                if random.randint(1, int(1 / mutation_rate)) == 1:
                    shape_mut_types = ['radius', 'shift', 'R', 'G', 'B', 'A']
                    shape_weights = [0.10, 0.10, 0.20, 0.20, 0.20, 0.20]
                    shape_mutation = random.choices(shape_mut_types, 
                                                    weights = shape_weights, 
                                                    k = 1)[0]
                    for shape in self.shape_genotype:
                        self.choose_mutation(obj = shape, mut_type = shape_mutation)
            elif mode == '6':
                ''' if -> for -> choose'''
                if random.randint(1, int(1 / mutation_rate)) == 1:
                    for shape in self.shape_genotype:
                        shape_mut_types = ['radius', 'shift', 'R', 'G', 'B', 'A']
                        shape_weights = [0.10, 0.10, 0.20, 0.20, 0.20, 0.20]
                        shape_mutation = random.choices(shape_mut_types, 
                                                        weights = shape_weights, 
                                                        k = 1)[0]
                        self.choose_mutation(obj = shape, mut_type = shape_mutation)
            else:
                '''choose a default means of mutation'''
                pass
        else:
            gene_mutation_types = ['add', 'subtract']
            gene_weights = [0.85, 0.15]
            gene_mutation = random.choices(gene_mutation_types, weights = gene_weights, k = 1)[0]
            if gene_mutation == 'add':
                self.shape_genotype.append(self.create_new_gene(factor = 0.5))
            else:
                if self.shape_genotype: self.shape_genotype.pop(0)
    
    def choose_mutation(self, obj: object, mut_type: str) -> None:
        if mut_type == 'radius':
            self.mutate_radius(shape = obj)
        elif mut_type == 'shift':
            self.mutate_coordinates(shape = obj)
        elif mut_type == 'R':
            self.mutate_color_R(shape = obj)
        elif mut_type == 'G':
            self.mutate_color_G(shape = obj)
        elif mut_type == 'B':
            self.mutate_color_B(shape = obj)
        elif mut_type == 'A':
            self.mutate_color_A(shape = obj)
        else:
            pass

    def mutate_coordinates(self, shape: object) -> None:
        x_shift = random.randint(-5, 5)
        y_shift = random.randint(-5, 5)
        shape.center = [shape.center[0] + x_shift, shape.center[1] + y_shift]
        shape.center[0] = min(max(shape.center[0], 0), shape.width - 1)
        shape.center[1] = min(max(shape.center[1], 0), shape.height - 1)
    
    def mutate_color_R(self, shape: object) -> None:
        R_shift = random.randint(-10, 10)
        shape.color[0] = shape.color[0] + R_shift
        shape.color[0] = min(max(shape.color[0], 0), 255)
        
    def mutate_color_G(self, shape: object) -> None:
        G_shift = random.randint(-10, 10)
        shape.color[1] = shape.color[1] + G_shift
        shape.color[1] = min(max(shape.color[1], 0), 255)
        
    def mutate_color_B(self, shape: object) -> None:
        B_shift = random.randint(-10, 10)
        shape.color[2] = shape.color[2] + B_shift
        shape.color[2] = min(max(shape.color[2], 0), 255)
        
    def mutate_color_A(self, shape: object) -> None:
        A_shift = random.randint(-10, 10)
        shape.color[3] = shape.color[3] + A_shift
        shape.color[3] = min(max(shape.color[3], 0), 255)
    
    def mutate_radius(self, shape: object) -> None:
        shift = random.randint(-1, 1)
        shape.radius = shape.radius + shift
    
    def sort_genotype(self, mode: int) -> None:
        '''
        | specs:
        | - design in modes to compare methods
        | - extensive documentation!!!
        | - mode #1: larger, more opaque shapes are drawn first
        | - mode #2: smaller, less opaque shapes are drawn first
        | - mode #3: smaller, more opaque shapes are drawn first
        | - mode #4: larger, less opaque shapes are drawn first
        |
        | - mode #5: larger shapes are drawn first
        | - mode #6: smaller shapes are drawn first
        | - mode #7: more opaque shapes are drawn first
        | - mode #8: less opaque shapes are drawn first
        '''
        if mode == '1':
            sort_func = lambda shape: (0.5 * shape.radius) + (0.5 * shape.color[-1])
            self.shape_genotype.sort(reverse = True, key = sort_func)
        elif mode == '2':
            func = lambda shape: (0.5 * shape.radius) + (0.5 * shape.color[-1])
            self.shape_genotype.sort(reverse = False, key = func)
        elif mode == '3':
            max_rad = max([shape.radius for shape in self.shape_genotype])
            sort_func = lambda shape: (0.5 * (max_rad - shape.radius)) + (0.5 * shape.color[-1])
            self.shape_genotype.sort(reverse = True, key = sort_func)
        elif mode == '4':
            max_opac = max([shape.color[-1] for shape in self.shape_genotype])
            sort_func = lambda shape: (0.5 * (max_opac - shape.color[-1])) + (0.5 * shape.radius)
            self.shape_genotype.sort(reverse = True, key = sort_func)
        elif mode == '5':
            self.shape_genotype.sort(reverse = True, key = lambda shape: shape.radius)
        elif mode == '6':
            self.shape_genotype.sort(reverse = False, key = lambda shape: shape.radius)
        elif mode == '7':
            self.shape_genotype.sort(reverse = True, key = lambda shape: shape.color[-1])
        elif mode == '8':
            self.shape_genotype.sort(reverse = False, key = lambda shape: shape.color[-1])
        else:
            '''opt for a random placement of shapes onto the canvas'''
            pass
    
    def create_new_gene(self, factor):
        '''
        - probablistically, an entire new gene will be generated
        '''
        return Shape(width = self.width, height = self.height, factor = factor)


if __name__ == "__main__":
    painting = Painting(width = 500, height = 500, size = 500)
    painting.show_painting()
    print('{}'.format(painting.canvas_genotype))
    for shape in painting.shape_genotype: print('{}'.format(shape))

Color: [219, 174, 154]
Color: [7, 3, 253, 146]; Radius: 327; Center: [166, 97]
Color: [121, 38, 230, 125]; Radius: 292; Center: [11, 421]
Color: [82, 93, 14, 180]; Radius: 265; Center: [42, 331]
Color: [217, 202, 213, 40]; Radius: 245; Center: [491, 330]
Color: [49, 144, 59, 234]; Radius: 236; Center: [232, 293]
Color: [105, 125, 251, 187]; Radius: 228; Center: [381, 54]
Color: [164, 155, 208, 64]; Radius: 220; Center: [140, 374]
Color: [239, 16, 222, 29]; Radius: 211; Center: [387, 25]
Color: [187, 125, 41, 29]; Radius: 205; Center: [94, 454]
Color: [56, 192, 8, 141]; Radius: 203; Center: [223, 117]
Color: [242, 222, 254, 221]; Radius: 202; Center: [204, 308]
Color: [185, 39, 225, 187]; Radius: 202; Center: [340, 312]
Color: [168, 215, 243, 128]; Radius: 190; Center: [128, 70]
Color: [118, 166, 15, 16]; Radius: 187; Center: [347, 85]
Color: [84, 18, 65, 253]; Radius: 181; Center: [117, 379]
Color: [14, 34, 205, 81]; Radius: 178; Center: [413, 194]
Color: [99, 141, 174, 164]; Radius: 1

In [11]:
class Figure:
    '''
    '''
    def __init__(self, path: str) -> None:
        self.path = path
        self.image = Image.open(self.path)
        self.image = self.convert_image()
        self.width, self.height = self.image.size
        self.data = self.get_color_data(self.image)
        self.paint_data = []
    
    @staticmethod
    def get_color_data(image: object) -> list:
        return np.array(Image.Image.getdata(image))

    def calculate_overall_fitness(self, input_painting: object) -> float:
        '''
        - for each pixel, determine the mean error of the color map
        '''
        input_painting = input_painting.phenotype.convert('RGB')
        self.paint_data = self.get_color_data(input_painting)
        diff1_percent = imgcompare.image_diff_percent(self.image, input_painting)
        return 100 - diff1_percent
    
    def calculate_r_fitness(self) -> float:
        return 255 - np.mean(np.abs(self.paint_data[:, 0] - self.data[:, 0]))
    
    def calculate_g_fitness(self) -> float:
        return 255 - np.mean(np.abs(self.paint_data[:, 1] - self.data[:, 1]))
    
    def calculate_b_fitness(self) -> float:
        return 255 - np.mean(np.abs(self.paint_data[:, 2] - self.data[:, 2]))

    def convert_image(self) -> object:
        return self.image.convert('RGB')
        

if __name__ == "__main__":
    target = Figure('../lib/test_target1.png')
    test_p = Painting(target.width, target.height, 3)
    print('{}'.format(target.data.shape))
    print('{}'.format(target.data[:30]))
    print('Overall Fitness: {}'.format(target.calculate_overall_fitness(test_p)))
    print('R Fitness: {}'.format(target.calculate_r_fitness()))
    print('G Fitness: {}'.format(target.calculate_g_fitness()))
    print('B Fitness: {}'.format(target.calculate_b_fitness()))

(45000, 3)
[[ 4  4 17]
 [ 3  4 16]
 [ 3  4 15]
 [ 3  4 14]
 [ 3  4 14]
 [ 1  4 14]
 [ 2  4 14]
 [ 3  4 14]
 [ 3  4 15]
 [ 3  4 16]
 [ 4  4 17]
 [ 4  4 18]
 [ 5  5 20]
 [ 5  5 22]
 [ 7  5 24]
 [ 8  5 26]
 [ 9  5 29]
 [11  5 31]
 [12  5 33]
 [12  6 35]
 [13  6 37]
 [15  6 39]
 [16  6 42]
 [16  6 43]
 [17  6 45]
 [18  7 47]
 [18  7 49]
 [19  7 51]
 [20  7 53]
 [20  7 54]]
Overall Fitness: 67.47547712418302
R Fitness: 177.36913333333334
G Fitness: 164.05793333333332
B Fitness: 199.459


In [12]:
class Population:
    '''
    '''
    def __init__(self, max_population: int, mutation_rate: float, target_path: str, size: int) -> None:
        self.max_population = max_population
        self.mutation_rate = mutation_rate
        self.target_path = target_path
        self.size = size
        self.target = Figure(self.target_path)
        self.population = [Painting(width = self.target.width,
                                    height = self.target.height,
                                    size = self.size) for _ in range(0, self.max_population)]
        self.children = []
    
    def choose_parent(self) -> object:
        weights = [painting.fitness for painting in self.population]
        return random.choices(self.population, weights = weights, k = 1)[0]
    
    def evaluate_population(self) -> None:
        for painting in self.population:
            painting.create_painting()
            painting.overall_fitness = self.target.calculate_overall_fitness(painting)
            painting.r_fitness = self.target.calculate_r_fitness() + painting.overall_fitness
            painting.g_fitness = self.target.calculate_g_fitness() + painting.overall_fitness
            painting.b_fitness = self.target.calculate_b_fitness() + painting.overall_fitness
    
    def generate_next_generation(self) -> None:
        '''
        - sexual reproduction
        - organisms in the population must be unique in order to mate
        '''
        # separate pop into 3 arrays
        # perform 3 crossovers (r, g, b)
        # add up 3 children arrays into one children array
        self.children = []
        r_children = []
        g_children = []
        b_children = []
        self.scale_fitness()

        self.sort_fitness(mode = 'R')
        for _ in range(0, len(self.population), 6):
            parent1 = self.choose_parent()
            parent2 = self.choose_parent()
            while parent1 == parent2: parent2 = self.choose_parent()
            child = parent1.crossover(parent_canvas_gen = parent2.canvas_genotype, 
                                      parent_shape_gen = parent2.shape_genotype, 
                                      mutation_rate = self.mutation_rate)
            r_children.append(child)
        
        self.sort_fitness(mode = 'G')
        for _ in range(0, len(self.population), 6):
            parent1 = self.choose_parent()
            parent2 = self.choose_parent()
            while parent1 == parent2: parent2 = self.choose_parent()
            child = parent1.crossover(parent_canvas_gen = parent2.canvas_genotype,
                                      parent_shape_gen = parent2.shape_genotype, 
                                      mutation_rate = self.mutation_rate)
            g_children.append(child)
        
        self.sort_fitness(mode = 'B')
        for _ in range(0, len(self.population), 6):
            parent1 = self.choose_parent()
            parent2 = self.choose_parent()
            while parent1 == parent2: parent2 = self.choose_parent()
            child = parent1.crossover(parent_canvas_gen = parent2.canvas_genotype,
                                      parent_shape_gen = parent2.shape_genotype, 
                                      mutation_rate = self.mutation_rate)
            b_children.append(child)
        
        for index in r_children: self.children.append(index)
        for index in g_children: self.children.append(index)
        for index in b_children: self.children.append(index)

    def adjust_population(self) -> None:
        if random.choice([0, 1]) == 0:
            self.population = self.population[: int(len(self.population) / 2)] + self.children
        else:
            self.population = self.population[int(len(self.population) / 2) :] + self.children
    
    def sort_fitness(self, mode: str) -> None:
        if mode == 'R':
            self.population.sort(reverse = True, key = lambda painting: painting.r_fitness)
        elif mode == 'G':
            self.population.sort(reverse = True, key = lambda painting: painting.g_fitness)
        elif mode == 'B':
            self.population.sort(reverse = True, key = lambda painting: painting.b_fitness)
        else: # SORT OVERALL FITNESS
            self.population.sort(reverse = True, key = lambda painting: painting.overall_fitness)
    
    def scale_fitness(self) -> None:
        mode = 'x'
        if mode == 'R': pass
        elif mode == 'G': pass
        elif mode == 'B': pass
        else:
            self.sort_fitness(mode = 'X')
            for i in range(0, len(self.population)):
                self.population[i].fitness = int(10 * (self.max_population / ((i + 1) ** 0.5)))

if __name__ == "__main__":
    pop = Population(max_population = 100, 
                     mutation_rate = 0.05, 
                     target_path = '../lib/test_target0.png', 
                     size = 3)

    pop.evaluate_population()
    pop.sort_fitness(mode = 'R')
    print('Best R fitness: {}'.format(pop.population[0].r_fitness))

    pop.sort_fitness(mode = 'G')
    print('Best G fitness: {}'.format(pop.population[0].g_fitness))

    pop.sort_fitness(mode = 'B')
    print('Best B fitness: {}'.format(pop.population[0].b_fitness))

    pop.sort_fitness(mode = 'X')
    print('Best overall fitness: {}'.format(pop.population[0].overall_fitness))

Best R fitness: 240.0445350762527
Best G fitness: 241.71226608569356
Best B fitness: 228.33608830791576
Best overall fitness: 66.96210312273058


In [13]:
class Evolution:
    '''
    '''
    def __init__(self) -> None:
        self.pop = Population(max_population = 60,
                              mutation_rate = 0.20,
                              target_path = '../lib/test_target0.png',
                              size = 5)
        self.generation = 1
        self.best_fitness = 0
    
    def evolve(self) -> None:
        count = 0
        # implement a canvas evolution
        # implement a shape evolution
        while count < 1000:
            self.pop.sort_fitness(mode = 'X')
            self.pop.population[0].save_painting(self.generation)
            self.pop.evaluate_population()
            self.save_best_painting()
            self.display_stats()
            self.pop.generate_next_generation()
            self.pop.adjust_population()
            self.generation += 1
            count += 1
    
    def save_best_painting(self) -> None:
        if self.pop.population[0].overall_fitness > self.best_fitness:
            self.pop.population[0].save_painting('_best')
            self.best_fitness = self.pop.population[0].overall_fitness
    
    def display_stats(self) -> None:
        print("--------------- STATS ---------------")
        print("Generation: {}".format(self.generation))
        print("Population Size: {}".format(len(self.pop.population)))
        print("Mean Fitness: {}".format(np.mean([i.overall_fitness for i in self.pop.population])))
        print("Std Fitness: {}".format(np.std([i.overall_fitness for i in self.pop.population])))
        print("Max Fitness: {}".format(max([i.overall_fitness for i in self.pop.population])))
        print("Min Fitness: {}".format(min([i.overall_fitness for i in self.pop.population])))
        print("-------------------------------------")

if __name__ == "__main__":
    evo = Evolution()
    evo.evolve()

--------------- STATS ---------------
Generation: 1
Population Size: 60
Mean Fitness: 52.22962149600581
Std Fitness: 5.245943642486015
Max Fitness: 62.68047833454369
Min Fitness: 37.69953231663036
-------------------------------------
--------------- STATS ---------------
Generation: 2
Population Size: 60
Mean Fitness: 54.35738626644073
Std Fitness: 4.67425939338579
Max Fitness: 62.67438973614137
Min Fitness: 41.94530718954248
-------------------------------------
--------------- STATS ---------------
Generation: 3
Population Size: 60
Mean Fitness: 56.717323650447845
Std Fitness: 4.714535304794299
Max Fitness: 65.18948438634713
Min Fitness: 41.94530718954248
-------------------------------------
--------------- STATS ---------------
Generation: 4
Population Size: 60
Mean Fitness: 57.72465811345114
Std Fitness: 4.126982284521022
Max Fitness: 65.14718954248366
Min Fitness: 42.692903413217145
-------------------------------------
--------------- STATS ---------------
Generation: 5
Populat

--------------- STATS ---------------
Generation: 36
Population Size: 60
Mean Fitness: 68.1017379488421
Std Fitness: 1.1784410286367102
Max Fitness: 70.71700217864924
Min Fitness: 65.21282401355604
-------------------------------------
--------------- STATS ---------------
Generation: 37
Population Size: 60
Mean Fitness: 68.70864494472686
Std Fitness: 0.9252259562947044
Max Fitness: 70.97974921326555
Min Fitness: 65.65001791333817
-------------------------------------
--------------- STATS ---------------
Generation: 38
Population Size: 60
Mean Fitness: 68.4048533204228
Std Fitness: 0.815223249872183
Max Fitness: 70.35144613894941
Min Fitness: 66.47847785039943
-------------------------------------
--------------- STATS ---------------
Generation: 39
Population Size: 60
Mean Fitness: 68.38917014443638
Std Fitness: 0.9494260896070049
Max Fitness: 71.25214814814815
Min Fitness: 66.1119147906076
-------------------------------------
--------------- STATS ---------------
Generation: 40
Pop

--------------- STATS ---------------
Generation: 71
Population Size: 60
Mean Fitness: 67.1906427176632
Std Fitness: 0.38519362782616334
Max Fitness: 67.95401016702978
Min Fitness: 66.02748002904866
-------------------------------------
--------------- STATS ---------------
Generation: 72
Population Size: 60
Mean Fitness: 67.11562759622366
Std Fitness: 0.3749907826440629
Max Fitness: 67.8723330912612
Min Fitness: 65.96687291212783
-------------------------------------
--------------- STATS ---------------
Generation: 73
Population Size: 60
Mean Fitness: 67.36569715161785
Std Fitness: 0.3586277335044249
Max Fitness: 67.94642653110627
Min Fitness: 66.11009440813362
-------------------------------------
--------------- STATS ---------------
Generation: 74
Population Size: 60
Mean Fitness: 67.28949994351652
Std Fitness: 0.3400685409906821
Max Fitness: 67.92280029048656
Min Fitness: 66.07349310094408
-------------------------------------
--------------- STATS ---------------
Generation: 75


--------------- STATS ---------------
Generation: 106
Population Size: 60
Mean Fitness: 70.7218147018478
Std Fitness: 0.33161994368086395
Max Fitness: 71.2553163882837
Min Fitness: 69.67860953764222
-------------------------------------
--------------- STATS ---------------
Generation: 107
Population Size: 60
Mean Fitness: 70.13037708383764
Std Fitness: 0.30440719617858925
Max Fitness: 70.65899007504237
Min Fitness: 69.17077705156137
-------------------------------------
--------------- STATS ---------------
Generation: 108
Population Size: 60
Mean Fitness: 70.2408976680384
Std Fitness: 0.3986435516572773
Max Fitness: 70.82816170418785
Min Fitness: 68.67595061728395
-------------------------------------
--------------- STATS ---------------
Generation: 109
Population Size: 60
Mean Fitness: 70.32747544581618
Std Fitness: 0.335742612556706
Max Fitness: 70.74044250786734
Min Fitness: 68.62879883805374
-------------------------------------
--------------- STATS ---------------
Generation: 

--------------- STATS ---------------
Generation: 141
Population Size: 60
Mean Fitness: 69.27266966836117
Std Fitness: 0.08385294589948335
Max Fitness: 69.32700459937061
Min Fitness: 68.89885064149117
-------------------------------------
--------------- STATS ---------------
Generation: 142
Population Size: 60
Mean Fitness: 72.67895037521183
Std Fitness: 0.05957946137966502
Max Fitness: 72.6955642701525
Min Fitness: 72.36338707334785
-------------------------------------
--------------- STATS ---------------
Generation: 143
Population Size: 60
Mean Fitness: 72.79285364318567
Std Fitness: 0.058862575571892964
Max Fitness: 72.81129411764707
Min Fitness: 72.4876456063907
-------------------------------------
--------------- STATS ---------------
Generation: 144
Population Size: 60
Mean Fitness: 72.50879173727104
Std Fitness: 0.0587287654072848
Max Fitness: 72.5439690147664
Min Fitness: 72.21361994674413
-------------------------------------
--------------- STATS ---------------
Generatio

--------------- STATS ---------------
Generation: 176
Population Size: 60
Mean Fitness: 73.75179201161946
Std Fitness: 0.1614148192983336
Max Fitness: 73.82228031953522
Min Fitness: 72.99437811667877
-------------------------------------
--------------- STATS ---------------
Generation: 177
Population Size: 60
Mean Fitness: 74.08045070604375
Std Fitness: 0.15350224700024553
Max Fitness: 74.16319535221496
Min Fitness: 73.34270636649723
-------------------------------------
--------------- STATS ---------------
Generation: 178
Population Size: 60
Mean Fitness: 72.64148264342774
Std Fitness: 0.22762032801939
Max Fitness: 72.75594674412974
Min Fitness: 71.84549213265552
-------------------------------------
--------------- STATS ---------------
Generation: 179
Population Size: 60
Mean Fitness: 71.83429871701767
Std Fitness: 0.12986618025847982
Max Fitness: 71.8884918905834
Min Fitness: 71.3843001694505
-------------------------------------
--------------- STATS ---------------
Generation: 

--------------- STATS ---------------
Generation: 211
Population Size: 60
Mean Fitness: 68.45164618736383
Std Fitness: 0.21889941124956516
Max Fitness: 68.60601694504962
Min Fitness: 67.66563059791818
-------------------------------------
--------------- STATS ---------------
Generation: 212
Population Size: 60
Mean Fitness: 67.89732164931816
Std Fitness: 0.20219577723944485
Max Fitness: 68.07028225611232
Min Fitness: 67.08032728152989
-------------------------------------
--------------- STATS ---------------
Generation: 213
Population Size: 60
Mean Fitness: 67.70358699265714
Std Fitness: 0.17558403331856046
Max Fitness: 67.83980634229
Min Fitness: 67.14026046961995
-------------------------------------
--------------- STATS ---------------
Generation: 214
Population Size: 60
Mean Fitness: 67.37950881949489
Std Fitness: 0.12256205207867589
Max Fitness: 67.46315758896151
Min Fitness: 66.79022028564512
-------------------------------------
--------------- STATS ---------------
Generatio

--------------- STATS ---------------
Generation: 246
Population Size: 60
Mean Fitness: 65.1064856612604
Std Fitness: 0.06453719707223375
Max Fitness: 65.12852868554829
Min Fitness: 64.8162827402566
-------------------------------------
--------------- STATS ---------------
Generation: 247
Population Size: 60
Mean Fitness: 64.8710000806907
Std Fitness: 0.10857239808060114
Max Fitness: 64.92656693294602
Min Fitness: 64.4163330912612
-------------------------------------
--------------- STATS ---------------
Generation: 248
Population Size: 60
Mean Fitness: 64.94239754700233
Std Fitness: 0.15685309811612821
Max Fitness: 65.28934979423869
Min Fitness: 64.19644638102154
-------------------------------------
--------------- STATS ---------------
Generation: 249
Population Size: 60
Mean Fitness: 64.95123466473008
Std Fitness: 0.2176190746438445
Max Fitness: 65.37358315177923
Min Fitness: 64.20456451222464
-------------------------------------
--------------- STATS ---------------
Generation:

--------------- STATS ---------------
Generation: 281
Population Size: 60
Mean Fitness: 64.82502948438633
Std Fitness: 0.10956145145522618
Max Fitness: 64.84477366255143
Min Fitness: 64.01134834180586
-------------------------------------
--------------- STATS ---------------
Generation: 282
Population Size: 60
Mean Fitness: 65.69085954974581
Std Fitness: 0.13292248800148268
Max Fitness: 65.7109658678286
Min Fitness: 64.68547083030744
-------------------------------------
--------------- STATS ---------------
Generation: 283
Population Size: 60
Mean Fitness: 65.98090173485032
Std Fitness: 0.013326133986587139
Max Fitness: 65.98263664972161
Min Fitness: 65.87854175744371
-------------------------------------
--------------- STATS ---------------
Generation: 284
Population Size: 60
Mean Fitness: 67.44538859033324
Std Fitness: 0.04308462437243793
Max Fitness: 67.45106560154926
Min Fitness: 67.11447300895668
-------------------------------------
--------------- STATS ---------------
Genera

--------------- STATS ---------------
Generation: 316
Population Size: 60
Mean Fitness: 65.13101718712178
Std Fitness: 0.0280509615845136
Max Fitness: 65.13790171871219
Min Fitness: 64.9840910191237
-------------------------------------
--------------- STATS ---------------
Generation: 317
Population Size: 60
Mean Fitness: 64.80936903090455
Std Fitness: 0.00693280270131104
Max Fitness: 64.81027160493826
Min Fitness: 64.75611716291455
-------------------------------------
--------------- STATS ---------------
Generation: 318
Population Size: 60
Mean Fitness: 64.83410183167919
Std Fitness: 0.07617637693752144
Max Fitness: 64.84485887194384
Min Fitness: 64.25119728879207
-------------------------------------
--------------- STATS ---------------
Generation: 319
Population Size: 60
Mean Fitness: 64.91238666989427
Std Fitness: 0.07345686003445465
Max Fitness: 64.93793851367707
Min Fitness: 64.44433599612685
-------------------------------------
--------------- STATS ---------------
Generati

--------------- STATS ---------------
Generation: 351
Population Size: 60
Mean Fitness: 67.44081465343339
Std Fitness: 0.10775214526250507
Max Fitness: 67.48335996126846
Min Fitness: 66.82737932703947
-------------------------------------
--------------- STATS ---------------
Generation: 352
Population Size: 60
Mean Fitness: 67.57401578310336
Std Fitness: 0.10727485263740681
Max Fitness: 67.61322682159283
Min Fitness: 67.02871362866134
-------------------------------------
--------------- STATS ---------------
Generation: 353
Population Size: 60
Mean Fitness: 67.77998302267409
Std Fitness: 0.16757014565083583
Max Fitness: 67.8249179375454
Min Fitness: 66.66085693536674
-------------------------------------
--------------- STATS ---------------
Generation: 354
Population Size: 60
Mean Fitness: 67.67017703542322
Std Fitness: 0.07016171947245542
Max Fitness: 67.6875371580731
Min Fitness: 67.26621544420237
-------------------------------------
--------------- STATS ---------------
Generati

--------------- STATS ---------------
Generation: 386
Population Size: 60
Mean Fitness: 63.943464213668996
Std Fitness: 0.1772042637048703
Max Fitness: 64.12561413701283
Min Fitness: 63.668643911885745
-------------------------------------
--------------- STATS ---------------
Generation: 387
Population Size: 60
Mean Fitness: 64.48901631566206
Std Fitness: 0.17329993374538388
Max Fitness: 64.59751924473494
Min Fitness: 64.06142822561122
-------------------------------------
--------------- STATS ---------------
Generation: 388
Population Size: 60
Mean Fitness: 65.05556284999598
Std Fitness: 0.10119118923332102
Max Fitness: 65.09508012587752
Min Fitness: 64.6647029774873
-------------------------------------
--------------- STATS ---------------
Generation: 389
Population Size: 60
Mean Fitness: 65.09462244815623
Std Fitness: 0.0202514667277993
Max Fitness: 65.09878286129266
Min Fitness: 64.95859017187121
-------------------------------------
--------------- STATS ---------------
Generat

--------------- STATS ---------------
Generation: 421
Population Size: 60
Mean Fitness: 65.78882762849997
Std Fitness: 0.7101696796817729
Max Fitness: 66.37347664003873
Min Fitness: 64.20393706124425
-------------------------------------
--------------- STATS ---------------
Generation: 422
Population Size: 60
Mean Fitness: 66.32073163882836
Std Fitness: 0.4943197455962207
Max Fitness: 66.54191236988623
Min Fitness: 65.09051755022998
-------------------------------------
--------------- STATS ---------------
Generation: 423
Population Size: 60
Mean Fitness: 66.45155000403454
Std Fitness: 0.2704199901261249
Max Fitness: 66.5201607358993
Min Fitness: 65.05408666182522
-------------------------------------
--------------- STATS ---------------
Generation: 424
Population Size: 60
Mean Fitness: 66.542122423949
Std Fitness: 0.29614691152737804
Max Fitness: 66.60444057129024
Min Fitness: 64.95920213023481
-------------------------------------
--------------- STATS ---------------
Generation: 

--------------- STATS ---------------
Generation: 456
Population Size: 60
Mean Fitness: 66.42937761639638
Std Fitness: 0.12497098197581738
Max Fitness: 66.44955313483419
Min Fitness: 65.50606051803437
-------------------------------------
--------------- STATS ---------------
Generation: 457
Population Size: 60
Mean Fitness: 66.26398799322199
Std Fitness: 0.13658263640766882
Max Fitness: 66.28588138465263
Min Fitness: 65.25140837569596
-------------------------------------
--------------- STATS ---------------
Generation: 458
Population Size: 60
Mean Fitness: 66.29493630275155
Std Fitness: 0.19267806477499014
Max Fitness: 66.35253836843378
Min Fitness: 65.27599515855725
-------------------------------------
--------------- STATS ---------------
Generation: 459
Population Size: 60
Mean Fitness: 66.03543458403938
Std Fitness: 0.008052530088505674
Max Fitness: 66.06797772936335
Min Fitness: 65.99436456063907
-------------------------------------
--------------- STATS ---------------
Gener

--------------- STATS ---------------
Generation: 491
Population Size: 60
Mean Fitness: 65.98610428467683
Std Fitness: 0.09494459146585883
Max Fitness: 66.11623723069474
Min Fitness: 65.60204502541757
-------------------------------------
--------------- STATS ---------------
Generation: 492
Population Size: 60
Mean Fitness: 65.57940411522632
Std Fitness: 0.04234452408521332
Max Fitness: 65.64899540062939
Min Fitness: 65.48244202372307
-------------------------------------
--------------- STATS ---------------
Generation: 493
Population Size: 60
Mean Fitness: 67.09689289114822
Std Fitness: 0.04267267597270281
Max Fitness: 67.17071120793997
Min Fitness: 66.96614669571532
-------------------------------------
--------------- STATS ---------------
Generation: 494
Population Size: 60
Mean Fitness: 66.08095692729766
Std Fitness: 0.17745334970956844
Max Fitness: 66.17296344710724
Min Fitness: 64.7915100459937
-------------------------------------
--------------- STATS ---------------
Generat

--------------- STATS ---------------
Generation: 526
Population Size: 60
Mean Fitness: 65.1126626966836
Std Fitness: 0.34960066221277586
Max Fitness: 65.40955700798838
Min Fitness: 62.800112321471794
-------------------------------------
--------------- STATS ---------------
Generation: 527
Population Size: 60
Mean Fitness: 65.59072069716777
Std Fitness: 0.15746200433403218
Max Fitness: 65.7363892519971
Min Fitness: 65.25252384410554
-------------------------------------
--------------- STATS ---------------
Generation: 528
Population Size: 60
Mean Fitness: 65.83431149842653
Std Fitness: 0.11962575855675224
Max Fitness: 65.89722585330429
Min Fitness: 65.35438779956426
-------------------------------------
--------------- STATS ---------------
Generation: 529
Population Size: 60
Mean Fitness: 66.22118873557653
Std Fitness: 0.13703698043837428
Max Fitness: 66.3201897845558
Min Fitness: 65.77036456063908
-------------------------------------
--------------- STATS ---------------
Generati

--------------- STATS ---------------
Generation: 561
Population Size: 60
Mean Fitness: 67.23923685951746
Std Fitness: 0.08468725229637714
Max Fitness: 67.27855531348342
Min Fitness: 66.74914935850884
-------------------------------------
--------------- STATS ---------------
Generation: 562
Population Size: 60
Mean Fitness: 67.55196914387153
Std Fitness: 0.17213684202012283
Max Fitness: 67.62823142096344
Min Fitness: 66.81263810215444
-------------------------------------
--------------- STATS ---------------
Generation: 563
Population Size: 60
Mean Fitness: 68.60220589042201
Std Fitness: 0.04632456043727602
Max Fitness: 68.63608811425804
Min Fitness: 68.28748099733721
-------------------------------------
--------------- STATS ---------------
Generation: 564
Population Size: 60
Mean Fitness: 68.58959941902687
Std Fitness: 0.05196164938413172
Max Fitness: 68.63134737351731
Min Fitness: 68.27131445170662
-------------------------------------
--------------- STATS ---------------
Genera

--------------- STATS ---------------
Generation: 596
Population Size: 60
Mean Fitness: 67.40080497054788
Std Fitness: 0.046687290760252645
Max Fitness: 67.41069958847737
Min Fitness: 67.07743790849673
-------------------------------------
--------------- STATS ---------------
Generation: 597
Population Size: 60
Mean Fitness: 67.86743316388285
Std Fitness: 0.058379850204645194
Max Fitness: 67.87775550714113
Min Fitness: 67.43629339143064
-------------------------------------
--------------- STATS ---------------
Generation: 598
Population Size: 60
Mean Fitness: 67.88236314048254
Std Fitness: 0.06015681917219234
Max Fitness: 67.89529314935851
Min Fitness: 67.45465214233842
-------------------------------------
--------------- STATS ---------------
Generation: 599
Population Size: 60
Mean Fitness: 67.71657032195596
Std Fitness: 1.4210854715202004e-14
Max Fitness: 67.71657032195594
Min Fitness: 67.71657032195594
-------------------------------------
--------------- STATS ---------------
G

--------------- STATS ---------------
Generation: 631
Population Size: 60
Mean Fitness: 65.87502519164043
Std Fitness: 0.25370216440645404
Max Fitness: 66.27343306705399
Min Fitness: 65.47000145243283
-------------------------------------
--------------- STATS ---------------
Generation: 632
Population Size: 60
Mean Fitness: 66.08890928750101
Std Fitness: 0.24901945969509257
Max Fitness: 66.47510820624547
Min Fitness: 65.64982425562818
-------------------------------------
--------------- STATS ---------------
Generation: 633
Population Size: 60
Mean Fitness: 66.82222299685307
Std Fitness: 0.18978717887884708
Max Fitness: 67.18539046235779
Min Fitness: 66.12503703703703
-------------------------------------
--------------- STATS ---------------
Generation: 634
Population Size: 60
Mean Fitness: 66.94407113693214
Std Fitness: 0.1596091571698761
Max Fitness: 67.38053546356815
Min Fitness: 66.49548099733721
-------------------------------------
--------------- STATS ---------------
Generat

--------------- STATS ---------------
Generation: 666
Population Size: 60
Mean Fitness: 69.37447307350924
Std Fitness: 0.2791298821683677
Max Fitness: 69.79634567901235
Min Fitness: 67.5602110869039
-------------------------------------
--------------- STATS ---------------
Generation: 667
Population Size: 60
Mean Fitness: 69.18319619139835
Std Fitness: 0.21469641236016654
Max Fitness: 69.6238044057129
Min Fitness: 68.54038247397725
-------------------------------------
--------------- STATS ---------------
Generation: 668
Population Size: 60
Mean Fitness: 67.20378600823045
Std Fitness: 0.2797602706189977
Max Fitness: 67.82939530380054
Min Fitness: 66.69482449770032
-------------------------------------
--------------- STATS ---------------
Generation: 669
Population Size: 60
Mean Fitness: 67.78527246025983
Std Fitness: 0.3073417999317428
Max Fitness: 68.26245267489712
Min Fitness: 67.29666618252239
-------------------------------------
--------------- STATS ---------------
Generation:

--------------- STATS ---------------
Generation: 701
Population Size: 60
Mean Fitness: 67.99267560719763
Std Fitness: 0.09911401023000943
Max Fitness: 68.01883902202857
Min Fitness: 67.36738997821351
-------------------------------------
--------------- STATS ---------------
Generation: 702
Population Size: 60
Mean Fitness: 68.65109891067537
Std Fitness: 0.06690142392065491
Max Fitness: 68.67348729121278
Min Fitness: 68.2638857419511
-------------------------------------
--------------- STATS ---------------
Generation: 703
Population Size: 60
Mean Fitness: 68.59615305414349
Std Fitness: 0.12366839199194442
Max Fitness: 68.62552214960058
Min Fitness: 67.69199903171145
-------------------------------------
--------------- STATS ---------------
Generation: 704
Population Size: 60
Mean Fitness: 68.47971454853547
Std Fitness: 0.24346828418682542
Max Fitness: 68.55029000242072
Min Fitness: 67.28548825950134
-------------------------------------
--------------- STATS ---------------
Generat

--------------- STATS ---------------
Generation: 736
Population Size: 60
Mean Fitness: 69.33071004599371
Std Fitness: 0.12898822643521293
Max Fitness: 69.37030646332607
Min Fitness: 68.76216702977487
-------------------------------------
--------------- STATS ---------------
Generation: 737
Population Size: 60
Mean Fitness: 68.94721600903736
Std Fitness: 0.027573654338602413
Max Fitness: 68.95104526748972
Min Fitness: 68.73541902687
-------------------------------------
--------------- STATS ---------------
Generation: 738
Population Size: 60
Mean Fitness: 69.26227063664972
Std Fitness: 0.011737020260498976
Max Fitness: 69.2640271120794
Min Fitness: 69.17211716291455
-------------------------------------
--------------- STATS ---------------
Generation: 739
Population Size: 60
Mean Fitness: 68.3987612361817
Std Fitness: 0.08563260532239683
Max Fitness: 68.41767320261438
Min Fitness: 67.92493052529653
-------------------------------------
--------------- STATS ---------------
Generatio

--------------- STATS ---------------
Generation: 771
Population Size: 60
Mean Fitness: 68.45789874929395
Std Fitness: 0.061551365725686244
Max Fitness: 68.47696344710724
Min Fitness: 68.23520116194626
-------------------------------------
--------------- STATS ---------------
Generation: 772
Population Size: 60
Mean Fitness: 68.19299759541677
Std Fitness: 0.050498961204725086
Max Fitness: 68.23372161704188
Min Fitness: 68.00136335027838
-------------------------------------
--------------- STATS ---------------
Generation: 773
Population Size: 60
Mean Fitness: 67.82677847171792
Std Fitness: 0.013257172034241229
Max Fitness: 67.82885306221254
Min Fitness: 67.72564124909223
-------------------------------------
--------------- STATS ---------------
Generation: 774
Population Size: 60
Mean Fitness: 67.92325616073592
Std Fitness: 0.0007378303855628448
Max Fitness: 67.92688259501332
Min Fitness: 67.92072427983538
-------------------------------------
--------------- STATS ---------------
G

--------------- STATS ---------------
Generation: 806
Population Size: 60
Mean Fitness: 69.6351619139837
Std Fitness: 0.3767596102387999
Max Fitness: 69.82279157588961
Min Fitness: 67.66886080852095
-------------------------------------
--------------- STATS ---------------
Generation: 807
Population Size: 60
Mean Fitness: 69.09018484628419
Std Fitness: 0.3706603659157485
Max Fitness: 69.29230113773905
Min Fitness: 67.14032244008715
-------------------------------------
--------------- STATS ---------------
Generation: 808
Population Size: 60
Mean Fitness: 69.30690796417333
Std Fitness: 0.44683476604289113
Max Fitness: 69.56217477608328
Min Fitness: 67.40691164366982
-------------------------------------
--------------- STATS ---------------
Generation: 809
Population Size: 60
Mean Fitness: 69.17282995239248
Std Fitness: 0.11742982268796795
Max Fitness: 69.29027935124667
Min Fitness: 69.05092616799806
-------------------------------------
--------------- STATS ---------------
Generatio

--------------- STATS ---------------
Generation: 841
Population Size: 60
Mean Fitness: 66.80114955216655
Std Fitness: 0.0018453828428736984
Max Fitness: 66.80474461389494
Min Fitness: 66.7923815056887
-------------------------------------
--------------- STATS ---------------
Generation: 842
Population Size: 60
Mean Fitness: 66.93496560961835
Std Fitness: 0.012536563394103088
Max Fitness: 66.94348874364562
Min Fitness: 66.84075720164608
-------------------------------------
--------------- STATS ---------------
Generation: 843
Population Size: 60
Mean Fitness: 67.36068748487048
Std Fitness: 0.0027199845494167087
Max Fitness: 67.36708012587751
Min Fitness: 67.35794722827401
-------------------------------------
--------------- STATS ---------------
Generation: 844
Population Size: 60
Mean Fitness: 67.49867738239328
Std Fitness: 0.0016244343582086482
Max Fitness: 67.50282643427741
Min Fitness: 67.49349987896393
-------------------------------------
--------------- STATS ---------------


--------------- STATS ---------------
Generation: 876
Population Size: 60
Mean Fitness: 66.19277049947551
Std Fitness: 0.18144373605381733
Max Fitness: 66.8232273057371
Min Fitness: 65.2001433067054
-------------------------------------
--------------- STATS ---------------
Generation: 877
Population Size: 60
Mean Fitness: 66.76788522553053
Std Fitness: 0.17052325002519836
Max Fitness: 67.17522730573711
Min Fitness: 65.56361558944565
-------------------------------------
--------------- STATS ---------------
Generation: 878
Population Size: 60
Mean Fitness: 66.53567749536028
Std Fitness: 0.20152171734753987
Max Fitness: 66.90917259743404
Min Fitness: 65.1999264100702
-------------------------------------
--------------- STATS ---------------
Generation: 879
Population Size: 60
Mean Fitness: 66.77333514080529
Std Fitness: 0.10234525645818124
Max Fitness: 67.11726942628903
Min Fitness: 66.59662454611474
-------------------------------------
--------------- STATS ---------------
Generatio

--------------- STATS ---------------
Generation: 911
Population Size: 60
Mean Fitness: 65.82593115468408
Std Fitness: 0.25308842377436197
Max Fitness: 66.21714064391189
Min Fitness: 65.46859937061244
-------------------------------------
--------------- STATS ---------------
Generation: 912
Population Size: 60
Mean Fitness: 66.36955145646736
Std Fitness: 0.2856361741383189
Max Fitness: 66.88589494069232
Min Fitness: 66.06725732268217
-------------------------------------
--------------- STATS ---------------
Generation: 913
Population Size: 60
Mean Fitness: 65.81129502138303
Std Fitness: 0.32639475918694866
Max Fitness: 66.20312757201646
Min Fitness: 65.39457564754298
-------------------------------------
--------------- STATS ---------------
Generation: 914
Population Size: 60
Mean Fitness: 65.50785921084484
Std Fitness: 0.3030058498052469
Max Fitness: 65.7125306221254
Min Fitness: 64.83750762527234
-------------------------------------
--------------- STATS ---------------
Generatio

--------------- STATS ---------------
Generation: 946
Population Size: 60
Mean Fitness: 66.34343426127653
Std Fitness: 0.2569839100076206
Max Fitness: 67.06312273057371
Min Fitness: 65.4639748244977
-------------------------------------
--------------- STATS ---------------
Generation: 947
Population Size: 60
Mean Fitness: 65.60641923666587
Std Fitness: 0.2708033059496096
Max Fitness: 66.39401984991528
Min Fitness: 64.72491503267975
-------------------------------------
--------------- STATS ---------------
Generation: 948
Population Size: 60
Mean Fitness: 65.89381941418543
Std Fitness: 0.28864688990648646
Max Fitness: 66.64250593076737
Min Fitness: 65.0250612442508
-------------------------------------
--------------- STATS ---------------
Generation: 949
Population Size: 60
Mean Fitness: 66.83264074880981
Std Fitness: 0.26279599190578584
Max Fitness: 67.41670297748729
Min Fitness: 65.84612345679012
-------------------------------------
--------------- STATS ---------------
Generation

--------------- STATS ---------------
Generation: 981
Population Size: 60
Mean Fitness: 61.86883395465182
Std Fitness: 0.11374154092007654
Max Fitness: 62.058542725732266
Min Fitness: 61.58515032679738
-------------------------------------
--------------- STATS ---------------
Generation: 982
Population Size: 60
Mean Fitness: 62.948555345759715
Std Fitness: 0.12227359948879082
Max Fitness: 63.120817235536194
Min Fitness: 62.67625659646575
-------------------------------------
--------------- STATS ---------------
Generation: 983
Population Size: 60
Mean Fitness: 63.00844722020495
Std Fitness: 0.1186581416805535
Max Fitness: 63.09368191721133
Min Fitness: 62.517255870249336
-------------------------------------
--------------- STATS ---------------
Generation: 984
Population Size: 60
Mean Fitness: 62.35276339869281
Std Fitness: 0.12935053545929717
Max Fitness: 62.471630113773905
Min Fitness: 61.90978261922053
-------------------------------------
--------------- STATS ---------------
Ge